#!/usr/bin/env python3
"""
IndexNow URL-selection logic for novatitan.net (PR #59).

This module is deliberately NETWORK-FREE and side-effect-free so it can be
unit-tested deterministically in CI (see tools/test_indexnow_lib.py, wired
into .github/workflows/seo-qa.yml as a hard gate) without ever calling a real
IndexNow endpoint from the test suite.

IndexNow is a push protocol operated by Microsoft Bing (participating engines
also include Yandex, Naver, Seznam.cz and Yep). It is NOT Google's indexing
API and does not directly notify OpenAI/ChatGPT -- ChatGPT Search's crawler
is OAI-SearchBot, a fully separate mechanism (see INDEXNOW.md). Bing's own
index does feed downstream AI answer engines (Copilot, and reportedly
historically ChatGPT Search) indirectly, which is the sole reason this
protocol is relevant to the 2026 AI-search-discovery objective.

--------------------------------------------------------------------------
WHY THIS EXISTS (changed-URL derivation, not full-site resubmission)
--------------------------------------------------------------------------
IndexNow's own operators warn against blasting a full sitemap on every
trivial commit. This module maps the set of files that changed in a given
git diff to the smaller set of PUBLIC, INDEXABLE canonical URLs that
actually need re-crawling, using the site's own build output (sitemap.xml)
as the single source of truth for "this URL is eligible to be submitted."

Because sitemap.xml is generated by jekyll-sitemap and is already hard-gated
by .github/workflows/seo-qa.yml to exclude noindex pages, redirect pages,
duplicate/legacy trees, and (per PR #58) quarantined/retired case studies,
any path that is NOT in the built sitemap is never eligible here -- this is
the primary defense against ever notifying a search engine about a
suppressed case study (amazon-security, va-healthcare, dyess-afb) or a
utility page (/thank-you/, /apply-tech/).

A second, explicit denylist below is defense-in-depth ONLY: it should never
actually trigger given the sitemap-membership check, but it exists so a
future regression in sitemap generation cannot silently reintroduce a
suppressed URL -- or the IndexNow key-verification file's own URL -- into an
IndexNow submission.
"""
from __future__ import annotations

import re
from urllib.parse import urlparse

# ---------------------------------------------------------------------------
# Defense-in-depth denylist. Every one of these should already be excluded
# from sitemap.xml (verified by seo-qa.yml and by PR #58); this list exists
# only to guarantee that a future sitemap regression cannot leak a
# submission for a suppressed/utility page.
# ---------------------------------------------------------------------------
DENYLIST_PATH_SUBSTRINGS = (
    "/thank-you/",
    "/apply-tech/",
    "/amazon-security/",
    "/va-healthcare/",
    "/dyess-afb/",
    # PR #59 review follow-up (2026-08): the IndexNow key-verification file
    # itself. The primary control keeping it out of submissions is
    # _config.yml's `sitemap: false` (it should never be a sitemap member at
    # all -- see INDEXNOW.md). This denylist entry is the same
    # defense-in-depth pattern as the suppressed case studies above: it
    # guarantees that even a future sitemap-generation regression could never
    # cause this tool to submit its own verification-key URL to IndexNow.
    "/0241145aa37aab753ad44f042523ea8b.txt",
)

# Files whose change means "a shared template/asset changed" -- in that case
# every page COULD have changed, so full resubmission of the (small, ~30-URL)
# sitemap is the officially-justified exception to the "no full resubmission
# on trivial commits" rule, rather than silently under-notifying.
GLOBAL_TEMPLATE_PREFIXES = (
    "_includes/",
    "_layouts/",
    "assets/css/",
    "assets/main.scss",
)
GLOBAL_TEMPLATE_EXACT = (
    "_config.yml",
)

# PR #59 review follow-up (2026-08): explicit, individually-verified list of
# `_data/*.yml` files that are consumed by SHARED, sitewide includes (i.e. a
# change here can affect every rendered page, the same justification as
# GLOBAL_TEMPLATE_PREFIXES/EXACT above). This is deliberately NOT a blanket
# "treat all _data/* as global" rule -- each entry below was confirmed by
# grepping its consuming include before being added:
#   - _data/nav.yml               <- _includes/header.html (site nav, every
#                                     page includes header.html via
#                                     _layouts/default.html)
#   - _data/testimonials.yml      <- _includes/head.html (AggregateRating/
#   - _data/testimonials_stats.yml   Review JSON-LD, every page includes
#                                     head.html via _layouts/default.html)
# `_data/home.yml` is DELIBERATELY EXCLUDED: verified (grep, 2026-08) that
# nothing in the repo references `site.data.home` -- it is dormant/unused
# legacy data with no template consumer, so it must not trigger a global
# resubmission.
SITEWIDE_DATA_FILES = (
    "_data/nav.yml",
    "_data/testimonials.yml",
    "_data/testimonials_stats.yml",
)

# Source files that drive generated pages via Liquid data/collections, where
# the changed source file does not map 1:1 onto a single output path.
CASE_STUDIES_DATA_FILE = "_data/case_studies.yml"
POSTS_DIR_PREFIX = "_posts/"


def is_global_template_change(changed_files: list[str]) -> bool:
    """True if a change touches a shared layout/include/config/sitewide-data
    file that could affect any page's rendered output, justifying
    full-sitemap resubmission.
    """
    for f in changed_files:
        if f in GLOBAL_TEMPLATE_EXACT:
            return True
        if f in SITEWIDE_DATA_FILES:
            return True
        if any(f.startswith(prefix) for prefix in GLOBAL_TEMPLATE_PREFIXES):
            return True
    return False


def sitemap_paths_from_urls(sitemap_urls: list[str]) -> set[str]:
    """Reduce absolute sitemap <loc> URLs to their url-path component
    (e.g. 'https://novatitan.net/services/' -> '/services/').
    """
    return {urlparse(u).path for u in sitemap_urls}


def map_changed_files_to_paths(
    changed_files: list[str], sitemap_paths: set[str]
) -> set[str]:
    """Map a list of git-changed repo-relative file paths to the subset of
    sitemap paths that plausibly correspond to them.

    Every returned path is guaranteed to already be a member of
    `sitemap_paths` (i.e. already proven indexable/canonical/non-noindex by
    the existing hard-gated sitemap build) -- this function only narrows,
    it never invents eligibility.
    """
    selected: set[str] = set()

    case_studies_changed = CASE_STUDIES_DATA_FILE in changed_files
    posts_changed = any(f.startswith(POSTS_DIR_PREFIX) for f in changed_files)

    if case_studies_changed:
        for p in sitemap_paths:
            if p == "/case-studies/" or p.startswith("/case-studies/"):
                selected.add(p)

    if posts_changed:
        for p in sitemap_paths:
            if p == "/blog/" or p.startswith("/blog/"):
                selected.add(p)

    for f in changed_files:
        # Direct 1:1 path match (covers static assets like PDFs, and any
        # file whose repo-relative path equals its public url-path exactly).
        direct = "/" + f
        if direct in sitemap_paths:
            selected.add(direct)

        # Jekyll "pretty" permalinks: foo/bar/index.html -> /foo/bar/
        if f.endswith("/index.html"):
            pretty = "/" + f[: -len("index.html")]
            if pretty in sitemap_paths:
                selected.add(pretty)
        elif f == "index.html":
            if "/" in sitemap_paths:
                selected.add("/")

    return selected


def apply_denylist(paths: set[str]) -> set[str]:
    """Defense-in-depth filter. See DENYLIST_PATH_SUBSTRINGS docstring above."""
    return {
        p
        for p in paths
        if not any(bad in p for bad in DENYLIST_PATH_SUBSTRINGS)
    }


def select_paths_to_submit(
    changed_files: list[str], sitemap_urls: list[str]
) -> set[str]:
    """Top-level selection: changed git files + built sitemap -> eligible
    url-paths to submit to IndexNow.
    """
    sitemap_paths = sitemap_paths_from_urls(sitemap_urls)

    if is_global_template_change(changed_files):
        selected = set(sitemap_paths)
    else:
        selected = map_changed_files_to_paths(changed_files, sitemap_paths)

    selected = apply_denylist(selected)

    # Final guarantee: never return anything not already in the sitemap.
    return {p for p in selected if p in sitemap_paths}


def paths_to_absolute_urls(paths: set[str], base_url: str) -> list[str]:
    base_url = base_url.rstrip("/")
    return sorted(base_url + p for p in paths)


KEY_FILENAME_RE = re.compile(r"^[a-zA-Z0-9-]{8,128}\.txt$")
KEY_VALUE_RE = re.compile(r"^[a-zA-Z0-9-]{8,128}$")


def validate_key_file(filename: str, content: str) -> list[str]:
    """Validate an IndexNow key-verification file per the spec:
    - filename is '{key}.txt'
    - key is 8-128 chars of [a-zA-Z0-9-]
    - file content is exactly the key (optionally with a trailing newline)
    Returns a list of problems (empty list == valid).
    """
    problems = []
    if not KEY_FILENAME_RE.match(filename):
        problems.append(
            f"key filename '{filename}' does not match required pattern "
            "'{8-128 chars of a-zA-Z0-9-}.txt'"
        )
        return problems

    key_from_name = filename[: -len(".txt")]
    stripped_content = content.strip()

    if not KEY_VALUE_RE.match(stripped_content):
        problems.append(
            f"key file content '{stripped_content}' is not 8-128 chars of "
            "[a-zA-Z0-9-]"
        )

    if stripped_content != key_from_name:
        problems.append(
            f"key file content '{stripped_content}' does not match its own "
            f"filename-derived key '{key_from_name}'"
        )

    return problems
